services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - OUTLOOK_CLIENT_ID=${OUTLOOK_CLIENT_ID}
      - OUTLOOK_CLIENT_SECRET=${OUTLOOK_CLIENT_SECRET}
      - OUTLOOK_REDIRECT_URL=${OUTLOOK_REDIRECT_URL}
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SESSION_SECRET=${SESSION_SECRET}
      - FE_URL=${FE_URL}
      - DOMAIN=${DOMAIN}
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
